/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClassdesignUI;

import Classdesignmodel.Address;
import Classdesignmodel.Contact;
import Classdesignmodel.Student;
import javax.swing.plaf.SplitPaneUI;
import javax.swing.JOptionPane;



/**
 *
 * @author 18572
 */
public class HuskyCardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HuskyCardJFrame
     */
     Student student ;
    public HuskyCardJFrame() {
        initComponents();
        this.student = new Student() ;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_nuid = new javax.swing.JTextField();
        txt_personalphoneno = new javax.swing.JTextField();
        txt_officeemailid = new javax.swing.JTextField();
        txt_officephoneno = new javax.swing.JTextField();
        txt_collegename = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        btn_Submit = new javax.swing.JButton();
        txt_personalemailid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_castreetname = new javax.swing.JTextField();
        txt_caapartmentno = new javax.swing.JTextField();
        txt_cacity = new javax.swing.JTextField();
        txt_cazipcode = new javax.swing.JTextField();
        txt_pastreetname = new javax.swing.JTextField();
        txt_paapartment = new javax.swing.JTextField();
        txt_pacity = new javax.swing.JTextField();
        txt_pazipcode = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jSplitPane2.setDividerLocation(400);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("NU ID");

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Personal Phone no.");

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("College Name");

        jLabel4.setBackground(new java.awt.Color(255, 255, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Office Phone no.");

        jLabel5.setBackground(new java.awt.Color(255, 255, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Office Email Id");

        jLabel6.setBackground(new java.awt.Color(255, 255, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("First Name");

        jLabel7.setBackground(new java.awt.Color(255, 255, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Personal Email Id");

        jLabel8.setBackground(new java.awt.Color(255, 255, 102));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Last Name");

        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });
        txt_firstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_firstnameKeyPressed(evt);
            }
        });

        txt_nuid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nuidActionPerformed(evt);
            }
        });
        txt_nuid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nuidKeyPressed(evt);
            }
        });

        txt_personalphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_personalphonenoActionPerformed(evt);
            }
        });
        txt_personalphoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_personalphonenoKeyPressed(evt);
            }
        });

        txt_officephoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_officephonenoKeyPressed(evt);
            }
        });

        txt_collegename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_collegenameActionPerformed(evt);
            }
        });
        txt_collegename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_collegenameKeyPressed(evt);
            }
        });

        txt_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lastnameActionPerformed(evt);
            }
        });
        txt_lastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lastnameKeyPressed(evt);
            }
        });

        btn_Submit.setText("Submit");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Current Address   -  ");

        jLabel12.setBackground(new java.awt.Color(255, 255, 102));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Permanent Address - ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Street Name");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Apartment No.");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("City/State");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Zipcode");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Apartment No.");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("City/State");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Zipcode");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Street Name");

        txt_castreetname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_castreetnameActionPerformed(evt);
            }
        });
        txt_castreetname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_castreetnameKeyPressed(evt);
            }
        });

        txt_caapartmentno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_caapartmentnoActionPerformed(evt);
            }
        });
        txt_caapartmentno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_caapartmentnoKeyPressed(evt);
            }
        });

        txt_cacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cacityActionPerformed(evt);
            }
        });
        txt_cacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cacityKeyPressed(evt);
            }
        });

        txt_cazipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cazipcodeActionPerformed(evt);
            }
        });
        txt_cazipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cazipcodeKeyPressed(evt);
            }
        });

        txt_pastreetname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pastreetnameActionPerformed(evt);
            }
        });
        txt_pastreetname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pastreetnameKeyPressed(evt);
            }
        });

        txt_paapartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_paapartmentActionPerformed(evt);
            }
        });
        txt_paapartment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_paapartmentKeyPressed(evt);
            }
        });

        txt_pacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pacityActionPerformed(evt);
            }
        });
        txt_pacity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pacityKeyPressed(evt);
            }
        });

        txt_pazipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pazipcodeActionPerformed(evt);
            }
        });
        txt_pazipcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pazipcodeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nuid))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_firstname))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_lastname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_collegename))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txt_officeemailid))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_personalphoneno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel16))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_personalemailid)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_castreetname, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_caapartmentno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_cacity, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(txt_cazipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_pastreetname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_paapartment, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 79, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_officephoneno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_pacity, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(txt_pazipcode))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nuid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_collegename, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_officephoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_officeemailid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_personalphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_personalemailid, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_castreetname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_caapartmentno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txt_cacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cazipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_pastreetname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_paapartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pazipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(36, 36, 36)
                .addComponent(btn_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jSplitPane2.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setForeground(new java.awt.Color(153, 255, 51));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        
        if(txt_nuid.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Some fields are remaining");   
        }
        else if(txt_officephoneno.getText().isEmpty())
        {
        JOptionPane.showMessageDialog(null, "Some fields are remaining ");   
        }
        else if(txt_personalphoneno.getText().isEmpty())
        { JOptionPane.showMessageDialog(null, "Some fields are remaining "); 
        }
        long nuid = Long.valueOf(txt_nuid.getText()) ;
        String firstName = txt_firstname.getText() ;
        String lastName = txt_lastname.getText() ;
        String collegeName = txt_collegename.getText() ;
        long officePhoneNo = Long.valueOf(txt_officephoneno.getText()) ;
        String  officeEmailId = txt_officeemailid.getText() ;
        long personalPhoneNo = Long.valueOf(txt_personalphoneno.getText()) ;
        String personalEmailId = txt_personalemailid.getText() ;
        String currentAddressStreetName = txt_castreetname.getText() ;
        String currentAddressApartmentNo = txt_caapartmentno.getText() ;
        String currentAddressCity = txt_cacity.getText() ;
        String currentAddressZipCode = txt_cazipcode.getText() ;
        String permanentAddressStreetName = txt_pastreetname.getText() ;
        String permanentAddressApartmentNo = txt_paapartment.getText() ;
        String permanentAddressCity = txt_pacity.getText() ;
        String permanentAddressZipCode = txt_pazipcode.getText() ;
        
      
        student.setNuid(nuid);
        student.setFirstName(firstName);
        student.setLastName(lastName);
        student.setCollegeName(collegeName);
        
       
        Contact officeContact = this.student.getOfficeContact() ;
        Contact personalContact = this.student.getPersonalContact() ;
        
        officeContact.setPhoneNo(officePhoneNo);
        officeContact.setEmailId(officeEmailId);
        personalContact.setEmailId(personalEmailId);
        personalContact.setPhoneNo(personalPhoneNo);
        
        
         Address currentAddress = this.student.getCurrentAddress() ;
        currentAddress.setStreetName(currentAddressStreetName);
        currentAddress.setApartmentNo(currentAddressApartmentNo);
        currentAddress.setCity(currentAddressCity);
        currentAddress.setZipCode(currentAddressZipCode);
        
        Address permanentAddress = this.student.getPermanentAddress() ;
        permanentAddress.setStreetName(permanentAddressStreetName);
        permanentAddress.setApartmentNo(permanentAddressApartmentNo);
        permanentAddress.setCity(permanentAddressCity);
        permanentAddress.setZipCode(permanentAddressZipCode);
        
         if( !firstName.isEmpty() && !lastName.isEmpty() && !collegeName.isEmpty() && !officeEmailId.isEmpty() && !personalEmailId.isEmpty() && !currentAddressStreetName.isEmpty() && !currentAddressApartmentNo.isEmpty() && !currentAddressCity.isEmpty() && !currentAddressZipCode.isEmpty() && !permanentAddressStreetName.isEmpty() && !permanentAddressApartmentNo.isEmpty() && !permanentAddressCity.isEmpty() && !permanentAddressZipCode.isEmpty())        
        {HuskyCardDetails HC = new HuskyCardDetails(student);
        jSplitPane2.setRightComponent(HC);
        }
        else
        { JOptionPane.showMessageDialog(null, "Enter correct value in all the fields");}
        
       
        
       txt_nuid.setText("");
       txt_firstname.setText("");
       txt_lastname.setText("");
       txt_collegename.setText("");
       txt_officephoneno.setText("");
       txt_officeemailid.setText("");
       txt_personalphoneno.setText("");
       txt_personalemailid.setText("");
       txt_castreetname.setText("");
       txt_caapartmentno.setText("");
       txt_cacity.setText("");
       txt_cazipcode.setText("");
       txt_pastreetname.setText("");
       txt_paapartment.setText("");
       txt_pacity.setText("");
       txt_pazipcode.setText("");
        
        
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void txt_collegenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_collegenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_collegenameActionPerformed

    private void txt_personalphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_personalphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_personalphonenoActionPerformed

    private void txt_nuidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nuidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nuidActionPerformed

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstnameActionPerformed

    private void txt_castreetnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_castreetnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_castreetnameActionPerformed

    private void txt_caapartmentnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_caapartmentnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_caapartmentnoActionPerformed

    private void txt_cacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cacityActionPerformed

    private void txt_cazipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cazipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cazipcodeActionPerformed

    private void txt_pastreetnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pastreetnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pastreetnameActionPerformed

    private void txt_paapartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_paapartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_paapartmentActionPerformed

    private void txt_pacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pacityActionPerformed

    private void txt_pazipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pazipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pazipcodeActionPerformed

    private void txt_nuidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nuidKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            txt_nuid.setEditable(true);
        }
        else{
            txt_nuid.setEditable(false);
        }
    }//GEN-LAST:event_txt_nuidKeyPressed

    private void txt_firstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_firstnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txt_firstname.setEditable(true);
        }
        else{
          txt_firstname.setEditable(false);
    }
    }//GEN-LAST:event_txt_firstnameKeyPressed

    private void txt_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastnameActionPerformed

    private void txt_lastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lastnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txt_lastname.setEditable(true);
        }
        else{
          txt_lastname.setEditable(false);
    }
    }//GEN-LAST:event_txt_lastnameKeyPressed

    private void txt_collegenameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_collegenameKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txt_collegename.setEditable(true);
        }
        else{
          txt_collegename.setEditable(false);
    }
    }//GEN-LAST:event_txt_collegenameKeyPressed

    private void txt_officephonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_officephonenoKeyPressed
        // TODO add your handling code here:
         char c =evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            txt_officephoneno.setEditable(true);
        }
        else{
            txt_officephoneno.setEditable(false);
        }
    }//GEN-LAST:event_txt_officephonenoKeyPressed

    private void txt_personalphonenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_personalphonenoKeyPressed
        // TODO add your handling code here:
         char c =evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            txt_personalphoneno.setEditable(true);
        }
        else{
            txt_personalphoneno.setEditable(false);
        }
    }//GEN-LAST:event_txt_personalphonenoKeyPressed

    private void txt_castreetnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_castreetnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txt_castreetname.setEditable(true);
        }
        else{
          txt_castreetname.setEditable(false);
    }
    }//GEN-LAST:event_txt_castreetnameKeyPressed

    private void txt_caapartmentnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_caapartmentnoKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            txt_caapartmentno.setEditable(true);
        }
        else{
            txt_caapartmentno.setEditable(false);
        }
    }//GEN-LAST:event_txt_caapartmentnoKeyPressed

    private void txt_cacityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cacityKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txt_cacity.setEditable(true);
        }
        else{
          txt_cacity.setEditable(false);
    }
    }//GEN-LAST:event_txt_cacityKeyPressed

    private void txt_cazipcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cazipcodeKeyPressed
        // TODO add your handling code here:
         char c =evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            txt_cazipcode.setEditable(true);
        }
        else{
            txt_cazipcode.setEditable(false);
        }
    }//GEN-LAST:event_txt_cazipcodeKeyPressed

    private void txt_pastreetnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pastreetnameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txt_pastreetname.setEditable(true);
        }
        else{
          txt_pastreetname.setEditable(false);
    }
    }//GEN-LAST:event_txt_pastreetnameKeyPressed

    private void txt_paapartmentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_paapartmentKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            txt_paapartment.setEditable(true);
        }
        else{
            txt_paapartment.setEditable(false);
        }
    }//GEN-LAST:event_txt_paapartmentKeyPressed

    private void txt_pacityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pacityKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
         if(Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txt_pacity.setEditable(true);
        }
        else{
          txt_pacity.setEditable(false);
    }
    }//GEN-LAST:event_txt_pacityKeyPressed

    private void txt_pazipcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pazipcodeKeyPressed
        // TODO add your handling code here:
        char c =evt.getKeyChar();
        if(Character.isDigit(c)||Character.isISOControl(c)){
            txt_pazipcode.setEditable(true);
        }
        else{
            txt_pazipcode.setEditable(false);
        }
    }//GEN-LAST:event_txt_pazipcodeKeyPressed
     
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HuskyCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HuskyCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HuskyCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HuskyCardJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HuskyCardJFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField txt_caapartmentno;
    private javax.swing.JTextField txt_cacity;
    private javax.swing.JTextField txt_castreetname;
    private javax.swing.JTextField txt_cazipcode;
    private javax.swing.JTextField txt_collegename;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_nuid;
    private javax.swing.JTextField txt_officeemailid;
    private javax.swing.JTextField txt_officephoneno;
    private javax.swing.JTextField txt_paapartment;
    private javax.swing.JTextField txt_pacity;
    private javax.swing.JTextField txt_pastreetname;
    private javax.swing.JTextField txt_pazipcode;
    private javax.swing.JTextField txt_personalemailid;
    private javax.swing.JTextField txt_personalphoneno;
    // End of variables declaration//GEN-END:variables
}
