/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ClassdesignUI;

import Classdesignmodel.Student;

/**
 *
 * @author 18572
 */
public class HuskyCardDetails extends javax.swing.JPanel {

    Student student;
    
    /**
     * Creates new form HuskyCardDetails
     */
    public HuskyCardDetails(Student student) {
        initComponents();
        this.student = student;
        
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contactpersonalTextField = new javax.swing.JLabel();
        contactofficeTextField = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        currentaddressTextField = new javax.swing.JLabel();
        permanentaddressTextField = new javax.swing.JLabel();
        contactofficeTextField1 = new javax.swing.JLabel();
        contactofficeTextField2 = new javax.swing.JLabel();
        contactofficeTextField3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        contactofficeTextField4 = new javax.swing.JLabel();
        permanentaddressTextField1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cc = new javax.swing.JLabel();
        txt_NuId = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        pazipcodeTextField = new javax.swing.JTextField();
        firstnameTextField = new javax.swing.JTextField();
        pacityTextField = new javax.swing.JTextField();
        paapartmentnoTextField = new javax.swing.JTextField();
        pastreetnameTextField = new javax.swing.JTextField();
        cazipcodeTextField = new javax.swing.JTextField();
        personalemailidTextField = new javax.swing.JTextField();
        officephonenoTextField = new javax.swing.JTextField();
        officeemailidTextField = new javax.swing.JTextField();
        caapartmentnoTextField = new javax.swing.JTextField();
        castreetnameTextField = new javax.swing.JTextField();
        personalphonenoTextField = new javax.swing.JTextField();
        collegenameTextField = new javax.swing.JTextField();
        cacityTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 119, 46));

        jLabel3.setText("NU ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 119, 46));

        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 119, 46));

        jLabel5.setText("Contact Info Personal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 306, 119, 20));

        jLabel6.setText("College Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 119, 46));

        jLabel7.setText("Contact Info Office");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 119, 46));

        contactpersonalTextField.setText("Phone No.");
        jPanel1.add(contactpersonalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        contactofficeTextField.setText("Email Id");
        jPanel1.add(contactofficeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 260, -1, -1));

        jLabel2.setText("Current Address");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 375, -1, -1));

        jLabel9.setText("Permanent Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        currentaddressTextField.setText("Email id");
        jPanel1.add(currentaddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        permanentaddressTextField.setText("Apt No.");
        jPanel1.add(permanentaddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 401, -1, -1));

        contactofficeTextField1.setText("Phone No.");
        contactofficeTextField1.setAlignmentY(0.0F);
        jPanel1.add(contactofficeTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 223, -1, -1));

        contactofficeTextField2.setText("Street Name");
        jPanel1.add(contactofficeTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 371, -1, 24));

        contactofficeTextField3.setText("Zipcode");
        jPanel1.add(contactofficeTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        jLabel8.setText("City/State");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        contactofficeTextField4.setText("Street Name");
        jPanel1.add(contactofficeTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, -1, 24));

        permanentaddressTextField1.setText("Apt No.");
        jPanel1.add(permanentaddressTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 509, -1, 40));

        jLabel10.setText("City/State");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, -1, -1));

        cc.setText("Zipcode");
        jPanel1.add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, -1, -1));

        txt_NuId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txt_NuId.setText("jTextField1");
        jPanel1.add(txt_NuId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 201, -1));

        lastnameTextField.setText("jTextField1");
        jPanel1.add(lastnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 200, -1));

        pazipcodeTextField.setText("jTextField1");
        jPanel1.add(pazipcodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 200, -1));

        firstnameTextField.setText("jTextField1");
        jPanel1.add(firstnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 200, -1));

        pacityTextField.setText("jTextField1");
        pacityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacityTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(pacityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 200, -1));

        paapartmentnoTextField.setText("jTextField1");
        jPanel1.add(paapartmentnoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 200, -1));

        pastreetnameTextField.setText("jTextField1");
        pastreetnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastreetnameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(pastreetnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 200, -1));

        cazipcodeTextField.setText("jTextField1");
        jPanel1.add(cazipcodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 200, -1));

        personalemailidTextField.setText("jTextField1");
        personalemailidTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalemailidTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(personalemailidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 200, -1));

        officephonenoTextField.setText("jTextField1");
        jPanel1.add(officephonenoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 200, -1));

        officeemailidTextField.setText("jTextField1");
        jPanel1.add(officeemailidTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 200, -1));

        caapartmentnoTextField.setText("jTextField1");
        jPanel1.add(caapartmentnoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 200, -1));

        castreetnameTextField.setText("jTextField1");
        jPanel1.add(castreetnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 200, -1));

        personalphonenoTextField.setText("jTextField1");
        personalphonenoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalphonenoTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(personalphonenoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 200, -1));

        collegenameTextField.setText("jTextField1");
        jPanel1.add(collegenameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 200, -1));

        cacityTextField.setText("jTextField1");
        jPanel1.add(cacityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 200, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Husky Card");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 270, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pastreetnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastreetnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pastreetnameTextFieldActionPerformed

    private void personalemailidTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalemailidTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalemailidTextFieldActionPerformed

    private void personalphonenoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalphonenoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personalphonenoTextFieldActionPerformed

    private void pacityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacityTextFieldActionPerformed

     void display()
    {
        txt_NuId.setText(String.valueOf(student.getNuid()));
        firstnameTextField.setText(this.student.getFirstName()) ;
        lastnameTextField.setText(this.student.getLastName()) ;
        collegenameTextField.setText(this.student.getCollegeName()) ;
        officephonenoTextField.setText(String.valueOf(this.student.getOfficeContact().getPhoneNo())) ;
        officeemailidTextField.setText(this.student.getOfficeContact().getEmailId()) ;
        personalphonenoTextField.setText(String.valueOf(this.student.getPersonalContact().getPhoneNo())) ;
        personalemailidTextField.setText(this.student.getPersonalContact().getEmailId()) ;
        castreetnameTextField.setText(this.student.getCurrentAddress().getStreetName()) ;
        caapartmentnoTextField.setText(this.student.getCurrentAddress().getApartmentNo()) ;
        cacityTextField.setText(this.student.getCurrentAddress().getCity()) ;
        cazipcodeTextField.setText(this.student.getCurrentAddress().getZipCode()) ;
        pastreetnameTextField.setText(this.student.getPermanentAddress().getStreetName()) ;
        paapartmentnoTextField.setText(this.student.getPermanentAddress().getApartmentNo()) ;
        pacityTextField.setText(this.student.getPermanentAddress().getCity()) ;
        pazipcodeTextField.setText(this.student.getPermanentAddress().getZipCode()) ;

    }
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caapartmentnoTextField;
    private javax.swing.JTextField cacityTextField;
    private javax.swing.JTextField castreetnameTextField;
    private javax.swing.JTextField cazipcodeTextField;
    private javax.swing.JLabel cc;
    private javax.swing.JTextField collegenameTextField;
    private javax.swing.JLabel contactofficeTextField;
    private javax.swing.JLabel contactofficeTextField1;
    private javax.swing.JLabel contactofficeTextField2;
    private javax.swing.JLabel contactofficeTextField3;
    private javax.swing.JLabel contactofficeTextField4;
    private javax.swing.JLabel contactpersonalTextField;
    private javax.swing.JLabel currentaddressTextField;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTextField officeemailidTextField;
    private javax.swing.JTextField officephonenoTextField;
    private javax.swing.JTextField paapartmentnoTextField;
    private javax.swing.JTextField pacityTextField;
    private javax.swing.JTextField pastreetnameTextField;
    private javax.swing.JTextField pazipcodeTextField;
    private javax.swing.JLabel permanentaddressTextField;
    private javax.swing.JLabel permanentaddressTextField1;
    private javax.swing.JTextField personalemailidTextField;
    private javax.swing.JTextField personalphonenoTextField;
    private javax.swing.JTextField txt_NuId;
    // End of variables declaration//GEN-END:variables
}
