/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

/**
 *
 * @author 18572
 */


import Model.Customer;


import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

public class EditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditJPanel
     */
    DeliveryPackage deliveryPackage ;
    private Product productViewed;
    public EditJPanel() {
        initComponents();
    }
     public EditJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        this.deliveryPackage = deliveryPackage ;
        displayProductList(); 
        displayPackageDetails();
    }
     public void displayProductList() {

        for (Product p : this.deliveryPackage.getProductlist()) {
            productComboBox.addItem((p.getProductId()));
        }

    }
     public void displayPackageDetails() {
        updatePackId.setText(String.valueOf(this.deliveryPackage.getPackageId()));
        updatepackWeight.setText(String.valueOf(this.deliveryPackage.getPackageWeight()));

        Customer customer = this.deliveryPackage.getCustomer();
        updatecId.setText(String.valueOf(customer.getCustomerId()));
        updatecName.setText(customer.getFullname());

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updatePackId = new javax.swing.JTextField();
        updateprodName = new javax.swing.JTextField();
        updatepackWeight = new javax.swing.JTextField();
        updateprodId = new javax.swing.JTextField();
        updateProdPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        updatecName = new javax.swing.JTextField();
        updatecId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        updateProduct = new javax.swing.JButton();
        showproductbtn = new javax.swing.JButton();
        updatePackage = new javax.swing.JButton();
        productComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 51));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });

        jLabel1.setText("Package Id");

        jLabel2.setText("Product Name");

        jLabel3.setText("weight");

        jLabel8.setText("Product Id");

        jLabel5.setText("price");

        updatePackId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePackIdActionPerformed(evt);
            }
        });

        updatepackWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepackWeightActionPerformed(evt);
            }
        });

        jLabel6.setText("Customer Name");

        jLabel7.setText("Customer Id");

        updatecId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecIdActionPerformed(evt);
            }
        });

        jLabel4.setText("Update");

        updateProduct.setText("Update Product");
        updateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductActionPerformed(evt);
            }
        });

        showproductbtn.setText("show");
        showproductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showproductbtnActionPerformed(evt);
            }
        });

        updatePackage.setText("Update Package");
        updatePackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePackageActionPerformed(evt);
            }
        });

        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(updatePackage))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(292, 292, 292)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(updateprodName, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                                .addComponent(updateProdPrice)
                                                .addComponent(updateprodId))
                                            .addGap(45, 45, 45))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(updatePackId, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(103, 103, 103)
                                                    .addComponent(updatepackWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(41, 41, 41)
                                                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(61, 61, 61)
                                                    .addComponent(showproductbtn)))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel2)
                                .addGap(241, 241, 241)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(updateProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(41, 41, 41)
                                .addComponent(updatecName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updatecId, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(updatePackId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(updatecName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatepackWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(updatecId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40)
                .addComponent(updatePackage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showproductbtn)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(updateprodId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(updateProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(updateprodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateProduct))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentMoved

    private void updatePackIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePackIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePackIdActionPerformed

    private void updatepackWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepackWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatepackWeightActionPerformed

    private void updatecIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatecIdActionPerformed

    private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
        // TODO add your handling code here:
//         String updateId = updatePackId.getText() ;
//        String updateweight = updatepackWeight.getText();
////        String updateproductId = packId.getText() ;
////        String updateproductName = prodName.getText() ;
////        String updateproductPrice = prodPrice.getText() ;
//        String updatecustomerName = updatecName.getText() ;
//        String updatecustomerId = updatecId.getText() ;
//        
//        this.deliveryPackage.setPackageId(Integer.valueOf(updateId) );
//         this.deliveryPackage.setPackageWeight(Double.valueOf(updateweight) );
//         
////         Product product = this.deliveryPackage.getProduct() ;
////         product.setProductId(Integer.valueOf(productId));
////         product.setProductName(productName);
////         product.setProductPrice(Double.valueOf(productPrice));
//         
//         Customer customer = this.deliveryPackage.getCustomer() ;
//         customer.setCustomerId(Integer.valueOf(updatecustomerId));
//         customer.setFullname(updatecustomerName);
//         
//         JOptionPane.showMessageDialog(null, "Package is updated");

             this.productViewed.setProductName(updateprodName.getText());
        this.productViewed.setProductPrice(Double.valueOf(updateProdPrice.getText()));
         
        
    }//GEN-LAST:event_updateProductActionPerformed

    private void showproductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showproductbtnActionPerformed
        // TODO add your handling code here:
        updateprodId.setEnabled(false);
        
        int pid = (int) productComboBox.getSelectedItem();
        Product prod = this.deliveryPackage.findProduct(pid);
         this.productViewed = prod;
        

        if (!prod.equals(null)) {
            updateprodId.setText(String.valueOf(pid));
            updateprodName.setText(prod.getProductName());
            updateProdPrice.setText(String.valueOf(prod.getProductPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
    }//GEN-LAST:event_showproductbtnActionPerformed

    private void updatePackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePackageActionPerformed
        // TODO add your handling code here:
         String updateId = updatePackId.getText() ;
        String updateweight = updatepackWeight.getText();
//        String updateproductId = packId.getText() ;
//        String updateproductName = prodName.getText() ;
//        String updateproductPrice = prodPrice.getText() ;
        String updatecustomerName = updatecName.getText() ;
        String updatecustomerId = updatecId.getText() ;
        
        this.deliveryPackage.setPackageId(Integer.valueOf(updateId) );
         this.deliveryPackage.setPackageWeight(Double.valueOf(updateweight) );
         
//         Product product = this.deliveryPackage.getProduct() ;
//         product.setProductId(Integer.valueOf(productId));
//         product.setProductName(productName);
//         product.setProductPrice(Double.valueOf(productPrice));
         
         Customer customer = this.deliveryPackage.getCustomer() ;
         customer.setCustomerId(Integer.valueOf(updatecustomerId));
         customer.setFullname(updatecustomerName);
         
         JOptionPane.showMessageDialog(null, "Package is updated");
    }//GEN-LAST:event_updatePackageActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JButton showproductbtn;
    private javax.swing.JTextField updatePackId;
    private javax.swing.JButton updatePackage;
    private javax.swing.JTextField updateProdPrice;
    private javax.swing.JButton updateProduct;
    private javax.swing.JTextField updatecId;
    private javax.swing.JTextField updatecName;
    private javax.swing.JTextField updatepackWeight;
    private javax.swing.JTextField updateprodId;
    private javax.swing.JTextField updateprodName;
    // End of variables declaration//GEN-END:variables
}
